language: php

php:
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"

env:
  - CONTAO_VERSION=~3.2.0
  - CONTAO_VERSION=~3.3.0
  - CONTAO_VERSION=~3.4.0
  - CONTAO_VERSION=~3.5.0
  - CONTAO_VERSION=~4.1.0

# Exclude impossible Contao Version combinations.
matrix:
  exclude:
    - php: "5.3"
      env: CONTAO_VERSION=~3.5.0
    - php: "5.3"
      env: CONTAO_VERSION=~4.1.0
    - php: "5.4"
      env: CONTAO_VERSION=~4.1.0

sudo: false

install:
  - cat ~/.composer/config.json
  - travis_retry composer self-update && composer --version
  - if [[ "$CONTAO_VERSION" =~ ^~4.* ]]; then composer require contao/core-bundle $CONTAO_VERSION --no-update; fi;
  - if [[ "$CONTAO_VERSION" =~ ^~3.* ]]; then composer require contao/core $CONTAO_VERSION --no-update; fi;
  - travis_retry composer update --prefer-dist --no-interaction -vvv

script: ant -keep-going

# Hack to make things work again - we can not use a shallow repository.
git:
  depth: 2147483647
